name: Docs Quality

on:
  pull_request:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".markdownlint*"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".markdownlint*"

jobs:
  lint-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config lychee.toml --no-progress --fail
            README.md docs/**/*.md
      - name: Upload lychee report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
